version: '3.8'

services:

  login-server:
    container_name: login-server
    image: login-server:latest
    build:
      context: .
      dockerfile: login-server.dockerfile
      args:
        PACKAGES: "less nano wget curl"
    ports:
      - "80:80"
    networks:
      - login-network
    volumes:
      - .:/var/www/html
    environment:
      - DEPLOYMENT_ENV=development
      - ENABLE_LOGS=true
      - MINIO_PORT=${MINIO_PORT}
      - MY_RESOURCES_BUCKET_NAME=${MY_RESOURCES_BUCKET_NAME}
      - MY_PRIV_RESOURCES_BUCKET_NAME=${MY_PRIV_RESOURCES_BUCKET_NAME}
      - MYSQL_DATABASE=${LOGIN_DB_NAME}
      - MYSQL_SERVER_PORT=${LOGIN_DB_SERVER_PORT}}
      - MINIO_LOGIN_SVR_USER=minioadmin
      - MINIO_LOGIN_SVR_PWD=minioadmin
    depends_on:
      - login-db-server
      - minio

  login-db-server:
    container_name: login-db-server
    image: login-db-server:latest
    networks:
      - login-network
    build:
      context: .
      dockerfile: login-db-server.dockerfile
      args:
        PACKAGES: "less nano wget curl"
    environment:
      MYSQL_DATABASE: '${LOGIN_DB_NAME}'
      MYSQL_HOST: 'localhost'
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'domingo.18.noviembre'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'domingo.18.noviembre'
    volumes:
      - ./dbs/login/entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./dbs/login/var:/var/lib/mysql
 
  minio:
    image: quay.io/minio/minio
    container_name: minio
    networks:
      - login-network
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./data:/data
    command: server /data

networks:
  login-network:
    driver: bridge

