apiVersion: v1
kind: PersistentVolume
metadata:
  name: login-db-server-pv
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /login-db-server/workspace/var/lib/mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: login-db-server-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

